In [4]:
import warnings
warnings.filterwarnings('ignore')

import numpy as np
from numpy import save
from numpy import load
import cv2 as cv
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

import seaborn as sns
import os
import pandas as pd
sns.set()

## Pre-process images and labels - (and save into numpy arrays)

In [5]:
max_images = 10000 # 61578
images= [] # np.empty((max_images, 424*424*3))
image_names = []
count = 0

In [6]:
dir = '/Users/hanna/Documents/ANLY590/590-GroupProject_drafts/galaxy-zoo-the-galaxy-challenge/images_training_rev1/'
dir

'/Users/hanna/Documents/ANLY590/590-GroupProject_drafts/galaxy-zoo-the-galaxy-challenge/images_training_rev1/'

In [7]:
count = 0
for filename in os.listdir(dir):
    if count >= max_images:
        break
    #print(os.path.join(dir, filename))
    img = cv.imread(os.path.join(dir, filename)) # .flatten()
    img = img.flatten()
    images.append(img)
    image_names.append(filename[:-4])
    count += 1

In [8]:
images = np.array(images)

In [9]:
# # SAVE pre-processed training data as numpy file
# save('images.npy', images)

In [9]:
solutions = pd.read_csv('/Users/hanna/Documents/ANLY590/590-GroupProject_drafts/galaxy-zoo-the-galaxy-challenge/training_solutions_rev1.csv')
solutions.head()

GalaxyID  Class1.1  Class1.2  Class1.3  Class2.1  Class2.2  Class3.1  \
0    100008  0.383147  0.616853  0.000000  0.000000  0.616853  0.038452   
1    100023  0.327001  0.663777  0.009222  0.031178  0.632599  0.467370   
2    100053  0.765717  0.177352  0.056931  0.000000  0.177352  0.000000   
3    100078  0.693377  0.238564  0.068059  0.000000  0.238564  0.109493   
4    100090  0.933839  0.000000  0.066161  0.000000  0.000000  0.000000   

   Class3.2  Class4.1  Class4.2  ...  Class9.3  Class10.1  Class10.2  \
0  0.578401  0.418398  0.198455  ...  0.000000   0.279952   0.138445   
1  0.165229  0.591328  0.041271  ...  0.018764   0.000000   0.131378   
2  0.177352  0.000000  0.177352  ...  0.000000   0.000000   0.000000   
3  0.129071  0.189098  0.049466  ...  0.000000   0.094549   0.000000   
4  0.000000  0.000000  0.000000  ...  0.000000   0.000000   0.000000   

   Class10.3  Class11.1  Class11.2  Class11.3  Class11.4  Class11.5  Class11.6  
0   0.000000   0.000000   0.092886        0.0        0.0        0.0   0.325512  
1   0.459950   0.000000   0.591328        0.0        0.0        0.0   0.000000  
2   0.000000   0.000000   0.000000        0.0        0.0        0.0   0.000000  
3   0.094549   0.189098   0.000000        0.0        0.0        0.0   0.000000  
4   0.000000   0.000000   0.000000        0.0        0.0        0.0   0.000000  

[5 rows x 38 columns]

In [10]:
y = []
for name in image_names:
    #print(solutions[solutions['GalaxyID']==int(name)])
    y.append(np.argmax(np.array(solutions[solutions['GalaxyID'] == int(name)].drop('GalaxyID', axis=1))))
y = np.array(y)
# print(y)

In [11]:
y

array([14,  1, 14, ..., 14, 14,  1])

In [13]:
# # SAVE pre-processed training labels as numpy file
# save('y_solutions.npy', y)

In [ ]:
# img = cv.imread(os.path.join(dir, '847006.jpg'))
# print(img)
# print(img.shape)

In [ ]:
# # Populate numpy array with images
# for filename in os.listdir(dir):
#     if count >= max_images:
#         break
#     #print(os.path.join(dir, filename))
#     image_names.append(filename[:-4])
#     img = cv.imread(os.path.join(dir, filename))
#     img = img.flatten()
        
#     count += 1

# print(images.shape)
# # print(images)

## ------------------------------------------------------------------------------------------------------
## START HERE TO LOAD IN DATA DIRECTLY FROM NUMPY FILES
## -------------------------------------------------------------------------------------------------------

In [3]:
# # %%time
# # TO LOAD DIRECTLY FROM SAVED NUMPY FILES:
# # https://stackoverflow.com/questions/55890813/how-to-fix-object-arrays-cannot-be-loaded-when-allow-pickle-false-for-imdb-loa/56062555

# np_load_old = np.load # save np.load
# np.load = lambda *a,**k: np_load_old(*a, allow_pickle=True, **k) # modify np.load default parameters

# # load the data saved from clean.py
# images = np.load('images.npy')
# y = np.load('y_solutions.npy')

# np.load = np_load_old # restore np.load for future normal usage

CPU times: user 4.55 ms, sys: 27.1 s, total: 27.1 s
Wall time: 33.5 s


In [12]:
# %%time
# split into train and test data/labels
X_train, X_test, y_train, y_test = train_test_split(images, 
                                                    y,
                                                   test_size=0.25,
                                                   random_state=0)

## Logistic Regression

In [13]:
logisticRegr = LogisticRegression()

In [14]:
%%time
logisticRegr.fit(X_train, y_train)

# CPU times: user 3h 30min 30s, sys: 6h 9min 17s, total: 9h 39min 47s
# Wall time: 8h 47min 34s
# Out[14]:
# LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
#                    intercept_scaling=1, l1_ratio=None, max_iter=100,
#                    multi_class='auto', n_jobs=None, penalty='l2',
#                    random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
#                    warm_start=False)

CPU times: user 3h 30min 30s, sys: 6h 9min 17s, total: 9h 39min 47s
Wall time: 8h 47min 34s


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
# save model

In [15]:
logisticRegr.predict(X_test[0].reshape(1,-1)) # predict for 1 image

array([14])

In [16]:
predictions = logisticRegr.predict(X_test) # make predictions on entire test data

In [17]:
logisticRegr.classes_

array([ 0,  1,  2, 13, 14])

In [18]:
logisticRegr.coef_.shape

(5, 539328)

#### LR Performance 

In [19]:
# training score 
logisticRegr.score(X_train, y_train)

# 0.9077333333333333 when data used 10000 images

0.9077333333333333

In [20]:
# TEST SCORE ***
logisticRegr.score(X_test, y_test)

# 0.582 when data used 10000 images

0.582

In [21]:
# confusion matrix
cm = metrics.confusion_matrix(y_test, predictions)
print(cm)

# [[  20   22    0   16  150]
#  [  27  302    0   39  283]
#  [   0    0    0    1    0]
#  [  19   28    0   20   71]
#  [  80  268    0   41 1113]]
# when data used 10000 images

[[  20   22    0   16  150]
 [  27  302    0   39  283]
 [   0    0    0    1    0]
 [  19   28    0   20   71]
 [  80  268    0   41 1113]]
